### ISSUE TITLE
支持 format 配置

### ISSUE THREAD

**Issue by Songggggr** [joyme123/thrift-ls#37]
想设置 indent 和 对齐方式 🙏

**Comment by joyme123** [comment]
> 设置添加逗号后，service 中不会自动添加

这个问题在这个 PR 中解决了。一些其他问题单独建 issue 跟踪了。这个 issue 先关闭了。新的问题可以单独建 issue 跟踪 @Songggggr 
https://github.com/joyme123/thrift-ls/pull/41
