### ISSUE TITLE
Support uuid

### ISSUE THREAD

**Issue by MisLink** [joyme123/thrift-ls#38]
Uuid is one of the base types in thrift[^1]. Now there is an error occured when idl contains uuid:

<img width="478" alt="图片" src="https://github.com/user-attachments/assets/bd13ece5-270b-4a51-a726-039361374163">

[^1]: https://thrift.apache.org/docs/idl#types

**Comment by joyme123** [comment]
Thanks for your feedback. Problem solved once you upgrade thriftls to v0.2.1

release here: https://github.com/joyme123/thrift-ls/releases/tag/v0.2.1
